name: Java CI with Gradle

on:
  pull_request:
    branches: [ main ]

env:
  APPLICATION: ${{ secrets.APPLICATION }}
  RESOURCE_PATH: ./src/main/resources/application.yml
  TEST_APPLICATION: ${{ secrets.TEST_APPLICATION }}
  TEST_RESOURCE_PATH: ./src/test/resources/application.yml
  S3_BUCKET_NAME: job-scanner-bucket

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # (0) 기본 체크아웃
      - name: Checkout
        uses: actions/checkout@v3

      # (1) JDK 11 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # (2) Application.yml 생성
      - uses: actions/checkout@v2
      - run: touch ${{env.RESOURCE_PATH}}
      - run: touch ${{env.TEST_RESOURCE_PATH}}
      - run: echo "${{env.APPLICATION}}" > ${{env.RESOURCE_PATH}}
      - run: echo "${{env.TEST_APPLICATION}}" > ${{env.TEST_RESOURCE_PATH}}
      - uses: actions/upload-artifact@v2
        with:
          name: application.yml
          path: ${{env.RESOURCE_PATH}}

      # (3) Gradle build
      - name: Build with Gradle
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: clean build
